spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 18
mybatis:
  mapper-locations: classpath:mappers/*.xml
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
Knife4j:
  enable: true
